version: '3.8'

services:
  # Database Service
  mongo:
    image: mongo:latest
    container_name: sweetshop_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - sweetshop-network

  # Backend Service
  backend:
    build: ./backend
    container_name: sweetshop_backend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017/sweetshop
      - JWT_SECRET=docker_secret_key
    depends_on:
      - mongo
    networks:
      - sweetshop-network

  # Frontend Service
  frontend:
    build: ./frontend
    container_name: sweetshop_frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - sweetshop-network

volumes:
  mongo-data:

networks:
  sweetshop-network:
    driver: bridge
